### ISSUE TITLE
Using outdated version of Adjust

### ISSUE THREAD

**Issue by aapaine** [segment-integrations/analytics-ios-integration-adjust#21]
Facebook rejects apps that use Adjust SDK version below 4.16.0 saying "using an old version of the Adjust SDK, may result in Facebook user access tokens being sent to a third-party analytics provider... please update the Adjust SDK to version 4.16.0 or above".
The Segment integration is using 'Adjust', '~> 4.15'. 
The current Adjust version is 4.17.2.

**Comment by n2parko** [comment]
@aapaine should be resolved with the latest release: https://github.com/segment-integrations/analytics-ios-integration-adjust/releases/tag/1.1.5
