### ISSUE TITLE
Adjust integration turned off?

### ISSUE THREAD

**Issue by onlyafly** [segment-integrations/analytics-ios-integration-adjust#4]
I am trying to setup this library in my app, but in the raw request in the Segment debugger is showing that the Adjust integration is disabled:

```
"integrations": {
  "Adjust": false
}
```

According to https://segment.com/docs/sources/mobile/ios/#integrations-in-debugger this means that the flag "tells the Segment servers that a request was already made directly from the device through a bundled SDK. That way we don’t send a duplicate request via our servers to those services"

Why is this disabled?

**Comment by f2prateek** [comment]
You are bundling the Ajjust SDK, so `analytics-ios` will cal the Adjust SDK with the event on the device. The `false` flag for the server to not send it via the server side integration (and end up in Adjust twice).

**Comment by onlyafly** [comment]
@f2prateek In that case, is the way I'm using now correct? Should I unbundle the Adjust SDK?
